---

name: Python package
on: [push, pull_request]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Execute python scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ovh_endpoint: ${{ secrets.ENDPOINT }}
          ovh_application_key: ${{ secrets.APPLICATION_KEY }}
          ovh_application_secret: ${{ secrets.APPLICATION_SECRET }}
          ovh_consumer_key: ${{ secrets.CONSUMER_KEY }}
        run: |
         python3 List-DNSZoneInDomain.py
         python3 List-Domain.py
